### ISSUE TITLE
Messages from Discord to Telegram doesn't work if they contain one *

### ISSUE THREAD

**Issue by Suppen** [trgwii/TediCross#6]
Two * works (like *this*)

**Comment by Suppen** [comment]
This appears to be due to Telegram's markdown parser not accepting a single *. Not sure how to fix this...

**Comment by mikaelssen** [comment]
Possible workaround is escaping all markdown. Markdown is not essential if it means that data is randomly lost.

**Comment by Suppen** [comment]
Fixed in commit b0ac12a
